// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0x7eo58pHGGuCeMx9nsZj3cg-9jqF_9I',
    appId: '1:805610748437:web:69e17be480ff373fabec1c',
    messagingSenderId: '805610748437',
    projectId: 'addition-23',
    authDomain: 'addition-23.firebaseapp.com',
    storageBucket: 'addition-23.appspot.com',
    measurementId: 'G-4ZJ50ZT71D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqB5A_p5VCA30PhLhupxns3TUfUGp87Fc',
    appId: '1:805610748437:android:11ff15145da87aa5abec1c',
    messagingSenderId: '805610748437',
    projectId: 'addition-23',
    storageBucket: 'addition-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRNB3gNPXVzx5ZaO0hBMZuGXKS0E-m6l4',
    appId: '1:805610748437:ios:adbc7af6b9f1767cabec1c',
    messagingSenderId: '805610748437',
    projectId: 'addition-23',
    storageBucket: 'addition-23.appspot.com',
    iosClientId: '805610748437-or4jsg11b0fn7645rsnbt851v6b4144r.apps.googleusercontent.com',
    iosBundleId: 'lakeside.imperial.addition23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRNB3gNPXVzx5ZaO0hBMZuGXKS0E-m6l4',
    appId: '1:805610748437:ios:ef8ee41bc08c5beeabec1c',
    messagingSenderId: '805610748437',
    projectId: 'addition-23',
    storageBucket: 'addition-23.appspot.com',
    iosClientId: '805610748437-m2tt2n0pt7mrqus024buv4ik4nfkcar4.apps.googleusercontent.com',
    iosBundleId: 'lakeside.imperial.addition23.RunnerTests',
  );
}
